baseURL = 'https://docs.luanti.org/'
languageCode = 'en-us'
title = 'Luanti Documentation'
theme = ['hugo-notice', 'hugo-book']
enableGitInfo = true

[params]
    BookTheme = 'auto'
    BookSection = '*'
    BookRepo = 'https://github.com/luanti-org/dev.luanti.org'
    BookEditPath = 'edit/master'
