name: Build with Hugo

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        id: runPrettier
        run: npm run format:check
      - name: Show formatter diff if it exists
        # https://docs.github.com/en/actions/learn-github-actions/expressions#failure
        if: ${{ failure() }}
        run: |
          npm run format:fix
          git diff > diff.txt
          npm install -g diff2html-cli
          diff2html -i file -s side -F diff.html -- diff.txt
      - name: Comment the diff as HTML if it exists
        # https://docs.github.com/en/actions/learn-github-actions/expressions#failure-with-conditions
        if: ${{ failure() && steps.runPrettier.conclusion == 'failure' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: diff.html
      - name: Build site to check for errors
        run: npm run build:ci
      - name: check that links are all valid
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "*.html"
          serverRoot: "./public/"
