name: Build with Hugo

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        id: runPrettier
        run: npm run format
      - name: Show formatter diff if it exists
        # https://docs.github.com/en/actions/learn-github-actions/expressions#failure
        if: ${{ failure() }}
        run: git diff
      - name: Build site to check for errors
        run: npm run build:ci
      - name: check that links are all valid
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "*.html"
          serverRoot: "./public/"
