name: Build with Hugo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Build site to check for errors
        run: npm run build:ci
      - name: check that links are all valid
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "*.html"
          serverRoot: "./public/"
