name: Build with Hugo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install depdencies
        run: npm ci
      - name: Build site to check for errors
        run: npm run build:ci